# 更新于：20230401
# 关注https://github.com/elnfnoosm/iOS_network
# 使用说明：
# 1、找到 {远程订阅} 部分，将MyProxy 的空缺替换为自己的机场订阅链接
# 2、将下方subscribe-url同样替换为自己的机场订阅链接，可以让Stash获取机场流量信息并在主页显示
subscribe-url: XXXX


#混合端口
mixed-port: 7890
#允许局域网
allow-lan: true
#绑定地址
bind-address: '*'
#模式:rule（规则） / global（全局代理）/ direct（全局直连）
mode: Rule
#日志级别（日志输出级别：分级如后silent / info / warning / error / debug级别越高日志输出量越大）
log-level: info
#外部控制器
external-controller: 127.0.0.1:9090

#DNS设置
dns:
  enable: true
  listen: 0.0.0.0:1053
  #DNS服务器
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  #DoH服务器
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  #列表中的域名将不会被解析为fake ip，这些域名相关的解析请求将会返回它们真实的IP地址
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'



proxy-providers:
  FlowerCloud:
    url: 
    interval: 86400
 
  Bygcloud:
    url: 
    interval: 86400

  Foo&Friends:
    url: 
    interval: 86400



proxy-groups:
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
  name: Accelerate
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Media.png
  name: Streaming
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Area.png
  name: Direct
  proxies:
  - DIRECT
  - Accelerate
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png
  name: Telegram
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
  name: Netflix
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Disney+.png
  name: Disney+
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Prime_Video.png
  name: PrimeVideo
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Windows_11.png
  name: MicroSoft
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple_1.png
  name: Apple
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png
  name: Game
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/iCloud.png
  name: PikPak
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Emby.png
  name: Emby
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
  name: Final
  proxies:
  - Accelerate
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/GLaDOS.png
  name: Bygcloud
  proxies: []
  type: select
  use:
  - Bygcloud
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/FNF.png
  name: Foo&Friends
  proxies: []
  type: select
  use:
  - Foo&Friends



rule-providers:
  Telegram:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list？r_parser.list&nore=
    interval: 86400

  Game:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Game/Game.list？r_parser.list&nore=
    interval: 86400

  Microsoft:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Microsoft/Microsoft.list？r_parser.list&nore=
    interval: 86400

  Apple:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Apple/Apple.list？r_parser.list&nore=
    interval: 86400

  Apple_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.txt
    interval: 86400

  Netflix:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Netflix/Netflix.list？r_parser.list&nore=
    interval: 86400

  Disney:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Disney/Disney.list？r_parser.list&nore=
    interval: 86400

  PrimeVideo:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/AmazonPrimeVideo/AmazonPrimeVideo.list？r_parser.list&nore=
    interval: 86400

  PikPak:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/PikPak/PikPak.list？r_parser.list&nore=
    interval: 86400

  Emby:
    behavior: classical
    url: https://raw.githubusercontent.com/CherryvilleZ/Configuration/main/EMBY.list？r_parser.list&nore=
    interval: 86400

  ProxyMedia:
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list？r_parser.list&nore=
    interval: 86400

  Proxy:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Proxy/Proxy.list？r_parser.list&nore=
    interval: 86400

  Proxy_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Domain.txt
    interval: 86400

  ChinaDomain:
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list？r_parser.list&nore=
    interval: 86400



rules:
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Game,Game
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Apple_Domain,Apple
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney+
  - RULE-SET,PrimeVideo,PrimeVideo
  - RULE-SET,PikPak,PikPak
  - RULE-SET,Emby,Emby
  - RULE-SET,ProxyMedia,Streaming
  - RULE-SET,Proxy,Accelerate
  - RULE-SET,Proxy_Domain,Accelerate
  - RULE-SET,ChinaDomain,Direct
  - GEOIP,CN,Direct
  - MATCH,Final