proxy-providers:
  FlowerCloud:
    url: 
    interval: 86400
 
  Bygcloud:
    url: 
    interval: 86400

  Foo&Friends:
    url: 
    interval: 86400


proxy-groups:
   - name: Accelerate
     type: select
     proxies:
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Direct Connect
     type: select
     proxies:
      - DIRECT
      - Accelerate    
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Telegram
     type: select
     proxies:
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Streaming
     type: select
     proxies:
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Netflix
     type: select
     proxies:
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Disney+
     type: select
     proxies:
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: PrimeVideo
     type: select
     proxies:
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: MicroSoft
     type: select
     proxies:
      - DIRECT   
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Apple
     type: select
     proxies:
      - DIRECT   
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Steam
     type: select
     proxies:
      - DIRECT   
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: PikPak
     type: select
     proxies:
      - DIRECT   
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Emby
     type: select
     proxies:
      - DIRECT   
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Final
     type: select
     proxies:
      - Accelerate   
      - DIRECT   
      - Bygcloud
      - Foo&Friends
     use:
      - FlowerCloud

   - name: Bygcloud
     type: select
     use:
      - Bygcloud

   - name: Foo&Friends
     type: select
     use:
      - Foo&Friends

  
rule-providers:
  Telegram:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    interval: 86400

  Steam:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    interval: 86400

  SteamCN:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml
    interval: 86400

  Microsoft:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400

  Xbox:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Xbox/Xbox.yaml
    interval: 86400
  
  GitHub:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
    interval: 86400

  Apple:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    interval: 86400

  Apple_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.txt
    interval: 86400

  Netflix:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
    interval: 86400

  Disney:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
    interval: 86400

  PrimeVideo:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml
    interval: 86400

  PikPak:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml
    interval: 86400

  Emby:
    behavior: classical
    url: https://raw.githubusercontent.com/YangXiaPeng/Personal/main/StashEmby.yaml
    interval: 86400

  GlobalMedia:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml
    interval: 86400

  GlobalMedia_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.txt
    interval: 86400

  Google:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    interval: 86400

  China:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.yaml
    interval: 86400

  China_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Domain.txt
    interval: 86400

  ChinaIp:
    behavior: ipcidr-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs_IP.txt
    interval: 86400

  Global:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml
    interval: 86400

  Global_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global_Domain.txt
    interval: 86400


rules:
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Steam,Steam
  - RULE-SET,SteamCN,Steam
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Xbox,Microsoft
  - RULE-SET,GitHub,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Apple_Domain,Apple
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney+
  - RULE-SET,PrimeVideo,PrimeVideo
  - RULE-SET,PikPak,PikPak
  - RULE-SET,Emby,Emby
  - RULE-SET,GlobalMedia,Streaming
  - RULE-SET,GlobalMedia_Domain,Streaming
  - RULE-SET,Google,Accelerate
  - RULE-SET,China,Direct Connect
  - RULE-SET,China_Domain,Direct Connect
  - RULE-SET,ChinaIp,Direct Connect,no-resolve
  - RULE-SET,Global,Accelerate
  - RULE-SET,Global_Domain,Accelerate
  - GEOIP,CN,DIRECT
  - MATCH,Final