proxy-providers:
  FlowerCloud:
    url: 
    interval: 86400
 
  Bygcloud:
    url: 
    interval: 86400

  Foo&Friends:
    url: 
    interval: 86400



proxy-groups:
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
  name: Accelerate
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Media.png
  name: Streaming
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Area.png
  name: Direct
  proxies:
  - DIRECT
  - Accelerate
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Telegram.png
  name: Telegram
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
  name: Netflix
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Disney+.png
  name: Disney+
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Prime_Video.png
  name: PrimeVideo
  proxies:
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Windows_11.png
  name: MicroSoft
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple_1.png
  name: Apple
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Steam.png
  name: Game
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Blinkload.png
  name: PikPak
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Emby.png
  name: Emby
  proxies:
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
  name: Final
  proxies:
  - Accelerate
  - DIRECT
  - Bygcloud
  - Foo&Friends
  type: select
  use:
  - FlowerCloud
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/GLaDOS.png
  name: Bygcloud
  proxies: []
  type: select
  use:
  - Bygcloud
- icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/FNF.png
  name: Foo&Friends
  proxies: []
  type: select
  use:
  - Foo&Friends



rule-providers:
  Telegram:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml
    interval: 86400

  Game:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml
    interval: 86400

  Microsoft:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    interval: 86400

  Apple:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    interval: 86400

  Apple_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.txt
    interval: 86400

  Netflix:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml
    interval: 86400

  Disney:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml
    interval: 86400

  PrimeVideo:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml
    interval: 86400

  PikPak:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.yaml
    interval: 86400

  Emby:
    behavior: classical
    url: https://raw.githubusercontent.com/YangXiaPeng/Personal/main/StashEmby.yaml
    interval: 86400

  ProxyMedia:
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
    interval: 86400

  Proxy:
    behavior: classical
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy.yaml
    interval: 86400

  Proxy_Domain:
    behavior: domain-text
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Domain.txt
    interval: 86400

  ChinaDomain:
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
    interval: 86400



rules:
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Game,Game
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Apple_Domain,Apple
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney+
  - RULE-SET,PrimeVideo,PrimeVideo
  - RULE-SET,PikPak,PikPak
  - RULE-SET,Emby,Emby
  - RULE-SET,ProxyMedia,Streaming
  - RULE-SET,Proxy,Accelerate
  - RULE-SET,Proxy_Domain,Accelerate
  - RULE-SET,ChinaDomain,Direct Connect
  - GEOIP,CN,Direct Connect
  - MATCH,Final